version: "3.8"

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: inzynierka
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - database-data:/var/lib/mysql

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"

volumes:
  database-data:
