version: "3.8"
name: link-up

services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: linkup_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - test-database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test-database-data:
