FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

ENV VITE_APP_API_URL=http://localhost:5500
ENV VITE_APP_SOCKET_URL=http://localhost:5501

COPY . .
RUN npm run build


FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
