FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

ENV VITE_APP_API_URL=http://localhost:5500
ENV VITE_APP_SOCKET_URL=http://localhost:5501

COPY . .

RUN npm run build


FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

RUN npm install --omit=dev

EXPOSE 3000

CMD ["npx", "vite", "preview", "--port", "3000", "--host"]
