version: "3.8"
name: link-up

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: inzynierka_test
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - test-database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test-database-data:
