version: "3.8"
name: link-up

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: linkup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - backend-files:/backend/files
    ports:
      - "5500:5500"

  socket:
    build:
      context: ../socket
      dockerfile: ../docker/Dockerfile.socket
    ports:
      - "5501:5501"

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "3000:3000"

volumes:
  database-data:
  backend-files:
