FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

ENV VITE_APP_API_URL=http://localhost:5500
ENV VITE_APP_SOCKET_URL=http://localhost:5501

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]