FROM node:latest

WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .

ENV VITE_APP_API_URL=http://localhost:5500
ENV VITE_APP_SOCKET_URL=http://localhost:5501

EXPOSE 3000

RUN npm run build

CMD ["npm", "run", "preview"]
