version: "3.8"
name: link-up

services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: linkup_e2e
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - e2e-database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  e2e-backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend.e2e
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - e2e-backend-files:/backend/files
    ports:
      - "5500:5500"

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "3000:3000"

volumes:
  e2e-database-data:
  e2e-backend-files:
