name: LinkUp Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Make script executable
        run: chmod +x ./docker-compose.sh

      - name: Start database
        run: ./docker-compose.sh test &

      - name: Wait for database to initialize
        run: |
          echo "Waiting for database to initialize..."
          until docker exec $(docker ps -qf "name=database") pg_isready -h localhost -p 5432; do
            sleep 1
          done
          echo "Database is ready."

      - name: Run Tests
        run: |
          cd backend
          npm install
          npm run test
