name: LinkUp Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          cd apps/backend
          npm ci

      - name: Copy envs for tests
        run: cp apps/backend/env.example apps/backend/.env.test

      - name: Run Tests
        run: |
          cd apps/backend
          npm run test
