name: LinkUp Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Copy envs for tests
        run: cp apps/backend/env.example apps/backend/.env.test

      - name: Run Backend Tests
        run: pnpm --filter backend test
