name: LinkUp Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Copy envs for tests
        run: cp backend/env.example backend/.env.test

      - name: Run Tests
        run: |
          cd backend
          npm install
          npm run test
